### ISSUE TITLE
AWS/EBS Namespace

### ISSUE THREAD

**Issue by ghost** [EagerELK/logstash-input-cloudwatch#4] opened 2015-08-26 15:16 UTC
How is the AWS/EBS namespace supposed to work? 

At first I tried 

```
input {
          cloudwatch {
            tag_name => 'monitored'
            tag_values => [ 'true' ]
            interval => 300
            period => 60
            namespace => 'AWS/EBS'
            metrics => ['VolumeReadBytes', 'VolumeWriteBytes', 'VolumeReadOps', 'VolumeWriteOps', 'VolumeTotalReadTime', 'VolumeTotalWriteTime', 'VolumeIdleTime', 'VolumeQueueLength', 'VolumeThroughputPercentage', 'VolumeConsumedReadWriteOps']
            region => 'ap-southeast-1'
            access_key_id => "xxxxx"
            secret_access_key => "xxxxxx"
            type => 'cloudwatch-ebs'
          }
        }
```

In that case I tries to get the EBS metrics from the EC2 instances.

So I tried to specify the instance in a more concrete way. Now it queries the correct instances, but still no return. 

```
input {
          cloudwatch {
            instances => ['vol-xxxxx', 'vol-xxxxx', 'vol-xxxxx', 'vol-xxxxx', 'vol-xxxxx']
            interval => 300
            period => 60
            namespace => 'AWS/EBS'
            metrics => ['VolumeReadBytes', 'VolumeWriteBytes', 'VolumeReadOps', 'VolumeWriteOps', 'VolumeTotalReadTime', 'VolumeTotalWriteTime', 'VolumeIdleTime', 'VolumeQueueLength', 'VolumeThroughputPercentage', 'VolumeConsumedReadWriteOps']
            region => 'ap-southeast-1'
            access_key_id => "xxxxx"
            secret_access_key => "xxxxxx"
            type => 'cloudwatch-ebs'
          }
        }
```

**Comment by jrgns** [comment] 2015-10-08 20:03
It's making the call, but not getting make meaningful data points. Will investigate this further.

**Comment by jrgns** [comment] 2015-10-09 13:10
The problem is that the input assumes that all the metrics uses `InstanceId` in all the namespaces. In AWS/EBS it actually uses `VolumeId`, and each namespace has it's own way to name and identify "instances".

I'll have to give this some thought to figure out a good way to abstract that away.

**Comment by ghost** [comment] 2015-10-10 07:35
Maybe just query all volumes by tag..

**Comment by jrgns** [comment] 2015-10-12 19:37
That's what I'm working towards. The code relies on having an instance id, but it should be possible to factor that out.

**Comment by jrgns** [comment] 2015-10-13 07:50
I'm going to address this as part of PR #2 . Closing this in favour of that.

**Closed as completed** 2015-10-13 07:50 UTC
Labels: bug
